---
apiVersion: v1
kind: Namespace
metadata:
  name: project
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: nfs
    name: wp-nfs-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/IT-Academy/nfs-data/sa2-21-22/alexv8288/front
    server: 192.168.37.105

#---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: db-pv-volume
#  labels:
#    type: nfs
#    name: db-nfs-vol
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    path: /mnt/IT-Academy/nfs-data/sa2-21-22/alexv8288/mysql
#    server: 192.168.37.105
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: project
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: wp-nfs-vol
      type: nfs
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: db-pv-claim
#  namespace: project
#  labels:
#    app: wordpress-db
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#  selector:
#    matchLabels:
#      name: db-nfs-vol
#      type: nfs
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: project
type: Opaque
data:
  password: c2VjcmV0cGFzcw==  #secretpass

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-front
  namespace: project
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wp
  namespace: project
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: wp.k8s-3.sa 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-front
                port:
                  number: 80