---
- hosts: host4
  vars:
    app_packages:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
      - python3-mysqldb
    #db_name: "wp_database"
    #db_user: "wp_user"
    #db_pass: "secretpass"
    MYSQL_DATABASE: "drupal"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "secretpass"
    MYSQL_ROOT_PASSWORD: "secretpass"
  pre_tasks:
  - name: Prepare. Install packages
    apt:
      name: "curl"
      state: latest
      update_cache: yes
  tasks:
  - name: Add MariaDB repos
    shell: |
      curl -LsS -O https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
      bash mariadb_repo_setup --mariadb-server-version=10.6
  - name: MySQL. Install packages
    apt:
      name: "{{ app_packages }}"
      state: latest
      update_cache: yes
    environment:
      DEBIAN_FRONTEND: noninteractive
  - name: MySQL. add bind-address
    ini_file:
      dest: /etc/mysql/my.cnf
      section: mysqld
      option: "bind-address"
      value: "{{ ansible_host }}"

  - name: restart mysql if necessary
    command: service mysql restart

  - mysql_db:
      name: "{{ MYSQL_DATABASE }}"
      state: absent
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_db:
      name: "{{ MYSQL_DATABASE }}"
      encoding: utf8
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_user:
      name: "{{ MYSQL_USER }}"
      host: "%"
      password: "{{ MYSQL_PASSWORD }}"
      priv: "{{ MYSQL_DATABASE }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: yes