name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        path: main
        
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        SOURCE: ./main
        WITH_V: true
        DEFAULT_BUMP: patch
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:  
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./main/Docker
        file: ./main/Docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress_app:${{ steps.tag.outputs.tag }}
        
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["./main/k8s/wp-deploy.yml"]'
      env:
        TAG: ${{ steps.tag.outputs.tag }}
        
    - name: Test manifests
      continue-on-error: true
      uses: instrumenta/kubeval-action@master
      with:
        files: ./main/k8s
        
    - uses: actions/checkout@v3
      with:
        repository: alexv8888/manifests
        ref: 'main'
        token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        path: deploy
        
    - name: Commit and push manifest
      run: |
        cp ./main/k8s/wp-deploy.yml ./deploy
        cd ./deploy
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "add image ${{ steps.tag.outputs.tag }}"
        git push origin main
        
        
